LibraryManagementSystem/CentralLibrary/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CentralLibrary.Models;
using Microsoft.EntityFrameworkCore;

namespace CentralLibrary.Controllers
{
    public class BookController : Controller
    {

        public readonly ApplicationDbContext _db;

        public BookController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var displayData = _db.BookTable.ToList();

            return View(displayData);
        }
        [HttpGet]
        public async Task<IActionResult> Index(string BookSearch)
        {
            ViewData["GetBookDetails"] = BookSearch;
            var displayData = from x in _db.BookTable select x;
            if (!String.IsNullOrEmpty(BookSearch))
            {
                displayData = displayData.Where(x => x.BookName.Contains(BookSearch));
            }
            return View(await displayData.AsNoTracking().ToListAsync());
        }

        //to create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Book book)
        {
            if (ModelState.IsValid)
            {
                _db.Add(book);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        //to edit

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var bookDetail = await _db.BookTable.FindAsync(id);
            return View(bookDetail);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                _db.Update(book);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(book);
        }
        //View book details
        public async Task<IActionResult> Details(int? id)
        {
            if(id == null)
            {
                return RedirectToAction("Index");
            }
            var bookDetails = await _db.BookTable.FindAsync(id);
            return View(bookDetails);
        }

        //to delete
        
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {

            var bookDetails = _db.BookTable.Where(x => x.Book_id == id).First();
                _db.Remove(bookDetails);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
         
            
        }
    }
}

LibraryManagementSystem/CentralLibrary/Controllers/CategoryController.cs
using CentralLibrary.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CentralLibrary.Controllers
{
    public class CategoryController : Controller
    {
        public readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var displayData = _db.Category.ToList();

            return View(displayData);
            
        }
        [HttpGet]
        public async Task<IActionResult> Index(string CategorySearch)
        {
            ViewData["GetCategoryDetails"] = CategorySearch;
            var displayData = from x in _db.Category select x;
            if (!String.IsNullOrEmpty(CategorySearch))
            {
                displayData = displayData.Where(x => x.CategoryName.Contains(CategorySearch));
            }
            return View(await displayData.AsNoTracking().ToListAsync());
        }


        //to create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _db.Add(category);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(category);
        }


        //to edit

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var categoryDetail = await _db.Category.FindAsync(id);
            return View(categoryDetail);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _db.Update(category);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(category);
        }
        //View book details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var categoryDetails = await _db.Category.FindAsync(id);
            return View(categoryDetails);
        }

        //to delete

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {

            var categoryDetails = _db.Category.Where(x => x.Category_id == id).First();
            _db.Remove(categoryDetails);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");


        }
    }
}

LibraryManagementSystem/CentralLibrary/Controllers/FineController.cs
using CentralLibrary.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CentralLibrary.Controllers
{
    public class FineController : Controller
    {
        public readonly ApplicationDbContext _db;

        public FineController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var displayData = _db.Fine.ToList();

            return View(displayData);
        }


        //to create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Fine fine)
        {
            if (ModelState.IsValid)
            {
                _db.Add(fine);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(fine);
        }

        //to edit

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var fineDetail = await _db.Fine.FindAsync(id);
            return View(fineDetail);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Fine fine)
        {
            if (ModelState.IsValid)
            {
                _db.Update(fine);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(fine);
        }
        //View book details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var fineDetails = await _db.Fine.FindAsync(id);
            return View(fineDetails);
        }

        //to delete

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {

            var fineDetails = _db.Fine.Where(x => x.Fine_id == id).First();
            _db.Remove(fineDetails);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");


        }
    }
}

LibraryManagementSystem/CentralLibrary/Controllers/LibraryCardController.cs
using CentralLibrary.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CentralLibrary.Controllers
{
    public class LibraryCardController : Controller
    {
        public readonly ApplicationDbContext _db;

        public LibraryCardController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var displayData = _db.LibraryCard.ToList();

            return View(displayData);
        }
        [HttpGet]
        public async Task<IActionResult> Index(string LibraryCardSearch)
        {
            ViewData["GetLibraryCardDetails"] = LibraryCardSearch;
            var displayData = from x in _db.LibraryCard select x;
            if (!String.IsNullOrEmpty(LibraryCardSearch))
            {
                displayData = displayData.Where(x => x.FullName.Contains(LibraryCardSearch));
            }
            return View(await displayData.AsNoTracking().ToListAsync());
        }

        //to create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(LibraryCard libraryCard)
        {
            if (ModelState.IsValid)
            {
                _db.Add(libraryCard);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(libraryCard);
        }

        //to edit

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var cardDetail = await _db.LibraryCard.FindAsync(id);
            return View(cardDetail);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(LibraryCard libraryCard)
        {
            if (ModelState.IsValid)
            {
                _db.Update(libraryCard);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(libraryCard);
        }
        //View  details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var cardDetails = await _db.LibraryCard.FindAsync(id);
            return View(cardDetails);
        }

        //to delete

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {

            var cardDetails = _db.LibraryCard.Where(x => x.Card_id == id).First();
            _db.Remove(cardDetails);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");


        }
    }
}

LibraryManagementSystem/CentralLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CentralLibrary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CentralLibrarySystem</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publication" asp-action="Index">Publications</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fine" asp-action="">Fine</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LibraryCard" asp-action="Index">Library Card</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="">Reservation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="AdminLogin" asp-controller="" asp-action="">Reports</a>
                        </li>
        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CentralLibrary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>